// Code generated by gen/generate.py from pandas_market_calendars. DO NOT EDIT.

package calendar

// America

// XNYS returns the New York Stock Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XNYS(years ...int) *Calendar { return load("xnys") }

// XNAS returns the NASDAQ calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XNAS(years ...int) *Calendar { return load("xnas") }

// XCBO returns the Chicago Board Options Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XCBO(years ...int) *Calendar { return load("xcbo") }

// XCBF returns the Cboe Futures Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XCBF(years ...int) *Calendar { return load("xcbf") }

// XTSE returns the Toronto Stock Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XTSE(years ...int) *Calendar { return load("xtse") }

// XMEX returns the Mexican Stock Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XMEX(years ...int) *Calendar { return load("xmex") }

// BVMF returns the B3 - Brasil Bolsa Balcão calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func BVMF(years ...int) *Calendar { return load("bvmf") }

// Europe

// XLON returns the London Stock Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XLON(years ...int) *Calendar { return load("xlon") }

// XAMS returns the Euronext Amsterdam calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XAMS(years ...int) *Calendar { return load("xams") }

// XBRU returns the Euronext Brussels calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XBRU(years ...int) *Calendar { return load("xbru") }

// XLIS returns the Euronext Lisbon calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XLIS(years ...int) *Calendar { return load("xlis") }

// XPAR returns the Euronext Paris calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XPAR(years ...int) *Calendar { return load("xpar") }

// XMIL returns the Borsa Italiana calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XMIL(years ...int) *Calendar { return load("xmil") }

// XMAD returns the Bolsa de Madrid calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XMAD(years ...int) *Calendar { return load("xmad") }

// XFRA returns the Frankfurt Stock Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XFRA(years ...int) *Calendar { return load("xfra") }

// XETR returns the Deutsche Börse Xetra calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XETR(years ...int) *Calendar { return load("xetr") }

// XSWX returns the SIX Swiss Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XSWX(years ...int) *Calendar { return load("xswx") }

// XDUB returns the Euronext Dublin calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XDUB(years ...int) *Calendar { return load("xdub") }

// XWBO returns the Wiener Börse calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XWBO(years ...int) *Calendar { return load("xwbo") }

// XSTO returns the Nasdaq Stockholm calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XSTO(years ...int) *Calendar { return load("xsto") }

// XCSE returns the Nasdaq Copenhagen calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XCSE(years ...int) *Calendar { return load("xcse") }

// XHEL returns the Nasdaq Helsinki calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XHEL(years ...int) *Calendar { return load("xhel") }

// XOSL returns the Oslo Børs calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XOSL(years ...int) *Calendar { return load("xosl") }

// Africa

// XJSE returns the Johannesburg Stock Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XJSE(years ...int) *Calendar { return load("xjse") }

// Asia/Pacific

// XBOM returns the BSE (Bombay Stock Exchange) calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XBOM(years ...int) *Calendar { return load("xbom") }

// XNSE returns the National Stock Exchange of India calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XNSE(years ...int) *Calendar { return load("xnse") }

// XBKK returns the Stock Exchange of Thailand calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XBKK(years ...int) *Calendar { return load("xbkk") }

// XSES returns the Singapore Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XSES(years ...int) *Calendar { return load("xses") }

// XHKG returns the Hong Kong Stock Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XHKG(years ...int) *Calendar { return load("xhkg") }

// XSHG returns the Shanghai Stock Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XSHG(years ...int) *Calendar { return load("xshg") }

// XSHE returns the Shenzhen Stock Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XSHE(years ...int) *Calendar { return load("xshe") }

// XKRX returns the Korea Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XKRX(years ...int) *Calendar { return load("xkrx") }

// XTAI returns the Taiwan Stock Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XTAI(years ...int) *Calendar { return load("xtai") }

// XJPX returns the Japan Exchange Group calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XJPX(years ...int) *Calendar { return load("xjpx") }

// XTKS returns the Tokyo Stock Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XTKS(years ...int) *Calendar { return load("xtks") }

// XASX returns the Australian Securities Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XASX(years ...int) *Calendar { return load("xasx") }

// XNZE returns the New Zealand Exchange calendar.
// Arguments are accepted for compatibility with scmhub/calendar and ignored:
// coverage is fixed by the generated data (see Calendar.Range).
func XNZE(years ...int) *Calendar { return load("xnze") }

// registryNames lists every generated calendar, in registry order.
var registryNames = []string{
	"xnys",
	"xnas",
	"xcbo",
	"xcbf",
	"xtse",
	"xmex",
	"bvmf",
	"xlon",
	"xams",
	"xbru",
	"xlis",
	"xpar",
	"xmil",
	"xmad",
	"xfra",
	"xetr",
	"xswx",
	"xdub",
	"xwbo",
	"xsto",
	"xcse",
	"xhel",
	"xosl",
	"xjse",
	"xbom",
	"xnse",
	"xbkk",
	"xses",
	"xhkg",
	"xshg",
	"xshe",
	"xkrx",
	"xtai",
	"xjpx",
	"xtks",
	"xasx",
	"xnze",
}
